In [18]:
import numpy
from matplotlib import pyplot
%matplotlib inline

In [19]:
L=1.0
nx=51
dx=L/(nx-1)
alpha=1.22e-3
q=0.0
x=numpy.linspace(0.0,L,num=nx)
T0=numpy.zeros_like(x)
T0[0]=100.0

In [20]:
from scipy import linalg

In [21]:
def lhs_operator():
    D=numpy.diag((2+1/sigma)*numpy.ones(nx-2))
    U=numpy.diag(-1.0*numpy.ones(nx-3),k=1)
    L=numpy.diag(-1.0*numpy.ones(nx-3),k=-1)
    A=D+U+L
    return A

In [22]:
def rhs_vector():
    b=T[1:-1]/sigma
    b[0]+=T[0]
    b[-1]+=q*dx

In [23]:
D=numpy.diag(2*numpy.ones(5),k=1)
print (D)

[[0. 2. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
def btcs(T0,nt,dt,dx,alpha,q):
    sigma=alpha*dt/dx**2
    A=lhs_operator()
    T=T0.copy()
    for n in range(nt):
        b=rhs_vector(T,sigma,q,dx)
        T[1:-1]=linalg.solv(A,b)
        T[-1]=T[-2]+q*dx
    return T

In [17]:
nt=1000
sigma=0.5
dt=sigma*nt**2/alpha
T=btcs(T0,nt,dt,dx,alpha,q)
pyplot.plot(x,T)

TypeError: rhs_vector() takes 0 positional arguments but 4 were given